name: spark-plot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Dev tools
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel

  # Testing
  - pytest
  - pytest-cov

  - pip:
    # Package deps
    - pyspark
    - pyarrow
    - matplotlib

    # Examples
    - jupyterlab
    - nycflights13

