name: spark-plot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Development conda deps
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # This project conda deps

  - pip:
    # Development pip deps
    - mkdocs
    - mkdocs-material
    - mkdocs-minify-plugin
    - pygments
    - pymdown-extensions

    # This project pip deps
